- CoPro/CoPro.xcodeproj/project.pbxproj
- CoPro/CoPro/Network/Config/Config.swift
- CoPro/CoPro/Network/Foundation/AFLogger.swift
- CoPro/CoPro/Network/Foundation/BaseAPI.swift
- CoPro/CoPro/Network/Foundation/BaseResponse.swift
- CoPro/CoPro/Network/Foundation/BaseTargetType.swift
- CoPro/CoPro/Network/Foundation/NetworkResult.swift
- CoPro/CoPro/Network/Foundation/URLConst.swift
- CoPro/CoPro/Util/Extension/UIColor++.swift
> Setting/#2 Add Network, Color file

- CoPro/CoPro.xcodeproj/project.pbxproj
- CoPro/CoPro/Presentation/Main/Model/noticeBoardDataModel.swift
- CoPro/CoPro/Presentation/Main/View/BottomSheetView.swift
- CoPro/CoPro/Presentation/Main/View/PassThroughView.swift
- CoPro/CoPro/Presentation/Main/View/noticeBoardTableViewCell.swift
- CoPro/CoPro/Presentation/Main/ViewController/MainViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/SortBottomSheetViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/recruitViewController.swift
- CoPro/CoPro/Util/CustomClass/RadioButton.swift
- CoPro/CoPro/Util/CustomClass/RadioButtonsStack.swift
- CoPro/CoPro/Util/Extension/UISegmented++.swift
- complete conflict
- Resolved: #11
> [Fix] Fix Error

- CoPro/CoPro.xcodeproj/project.pbxproj
- CoPro/CoPro.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- CoPro/CoPro/Network/API/Board/BoardAPI.swift
- CoPro/CoPro/Network/DTO/Board/Request/DetailBoardRequestBody.swift
- CoPro/CoPro/Network/DTO/Board/Response/BoardDTO.swift
- CoPro/CoPro/Network/DTO/Board/Response/DetailBoardDTO.swift
- CoPro/CoPro/Network/Router/BoardRouter/BoardRouter.swift
- CoPro/CoPro/Presentation/Main/Model/BoardDataModel.swift
- CoPro/CoPro/Presentation/Main/Model/CommentDataModel.swift
- CoPro/CoPro/Presentation/Main/Model/DetailBoardDateModel.swift
- CoPro/CoPro/Presentation/Main/Model/DetailHeartDataModel.swift
- CoPro/CoPro/Presentation/Main/View/CommentTableViewCell.swift
- CoPro/CoPro/Presentation/Main/View/noticeBoardTableViewCell.swift
- CoPro/CoPro/Presentation/Main/ViewController/AddPostViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/DetailBoardViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/MainViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/ReportBottomSheetViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/SortBottomSheetViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/recruitViewController.swift
- CoPro/CoPro/Util/Component/AppController.swift
- CoPro/CoPro/Util/CustomClass/RadioButtonsStack.swift
- 게시판 뷰의 기능 구현 완료
디자인 미완성인 스크랩 기능, 게시글의 CUD를 제외한 게시판 뷰의 모든 기능을 구현완료했습니다. 
- Resolved: #22
> [Feat] #22 - BoardView except scrap, post cud

- CoPro/CoPro.xcodeproj/project.pbxproj
- CoPro/CoPro/Network/DTO/Card/CardDTO.swift
- Xcode가 코드 훔처간거 돌려놓음
- Resolved: #
> [Fix] 코드 도둑놈 혼내주기

- CoPro/CoPro.xcodeproj/project.pbxproj
- CoPro/CoPro/Application/Info.plist
- CoPro/CoPro/CoProDebug.entitlements
- CoPro/CoPro/CoProRelease.entitlements
- CoPro/CoPro/Presentation/Login/View/LoginView.swift
- CoPro/CoPro/Presentation/Login/ViewController/LoginViewController.swift
- 애플 로그인
| GIF | <img src = "https://github.com/codingBottle/CoPro-iOS/assets/112539563/515054f9-da8a-418d-9088-80d373752150" width ="250">|
- Resolved: #27
> [Feat] #27 - Signin With Apple

- CoPro/CoPro.xcodeproj/project.pbxproj
- CoPro/CoPro/Application/Info.plist
- CoPro/CoPro/Application/SceneDelegate.swift
- CoPro/CoPro/Presentation/BottomTab/ViewController/BottomTabController.swift
- CoPro/CoPro/Presentation/Login/ViewController/LoginViewController.swift
- BottomTabBar 적용
- 추가로 연동할 화면 추가 위치 
BottomTabBar > MARK확인
- Resolved: #31
> [Feat] #31 - BottomTabBar

- CoPro/CoPro.xcodeproj/project.pbxproj
- CoPro/CoPro/Network/API/Login/LoginAPI.swift
- CoPro/CoPro/Network/DTO/Login/LoginDTO.swift
- CoPro/CoPro/Presentation/Login/ViewController/LoginViewController.swift
- 구글 로그인 구조 변경
- 기존 keychain idToken 수정 => accessToken, refreshToken
- 구글 로그인 firebase 관련 코드 삭제
- accessToken, refreshToken 으로 기존 idToken 변경해서 keychain 관련 부분 수정하셔야해요 accessToken 으로
- accessToken, refreshToken 으로 기존 idToken 변경해서 keychain 관련 부분 수정하셔야해요 accessToken 으로
- Resolved: #35
> [Feat] #35 - Refactor Google SignIn Firebase => Oauth2.0 

- CoPro/CoPro.xcodeproj/project.pbxproj
- CoPro/CoPro/Application/Info.plist
- CoPro/CoPro/Application/SceneDelegate.swift
- CoPro/CoPro/Network/API/Card/CardAPI.swift
- CoPro/CoPro/Network/API/Login/GitHubLoginManager.swift
- CoPro/CoPro/Network/API/Login/LoginAPI.swift
- CoPro/CoPro/Network/Config/Config.swift
- CoPro/CoPro/Network/DTO/Card/CardDTO.swift
- CoPro/CoPro/Presentation/BottomTab/ViewController/BottomTabController.swift
- CoPro/CoPro/Presentation/Card/View/CardCollectionCellView.swift
- CoPro/CoPro/Presentation/Card/View/CardView.swift
- CoPro/CoPro/Presentation/Card/View/MiniCardGridView.swift
- CoPro/CoPro/Presentation/Card/ViewController/CardViewController.swift
- CoPro/CoPro/Presentation/Login/ViewController/LoginViewController.swift
- apple, github oauth signin
- refreshAccessToken
idtoken말고 accessToken으로 keychain에 저장해요
- Resolved: #35
> [Feat] #35 - Refactor SignIn with Firebase => Oauth2.0 

- CoPro/CoPro/Network/API/Login/LoginAPI.swift
- CoPro/CoPro/Presentation/BottomTab/ViewController/BottomTabController.swift
- 컨플릭으로 날라간 깃허브 로그인 에러 알림창, 바텀탭 아이콘 복구
- Resolved: #44
> [Refactor] Github Signin Error Alert  & BottomTabBar Icon

- CoPro/CoPro.xcodeproj/project.pbxproj
- CoPro/CoPro/Network/API/Card/CardAPI.swift
- CoPro/CoPro/Network/DTO/MyProfile/LikeProfileDTO.swift
- CoPro/CoPro/Presentation/MyProfile/ViewController/LikeProfileViewController.swift
- CoPro/CoPro/Presentation/MyProfile/ViewController/MyProfileViewController.swift
- 관심프로필 화면 추가
- 마이프로필 뷰 네비게이션 커스텀 
- Resolved: #47
> [Feat] #47 - 관심프로필 화면 추가

- CoPro/CoPro/Network/API/Login/LoginAPI.swift
- CoPro/CoPro/Presentation/Chat/View/ChannelTableViewCell.swift
- CoPro/CoPro/Presentation/Chat/ViewController/ChannelViewController.swift
- CoPro/CoPro/Presentation/MyProfile/ViewController/EditGithubModalViewController.swift
- CoPro/CoPro/Presentation/MyProfile/ViewController/MyProfileViewController.swift
> [Feat] #43 - Additional modifications

- CoPro/CoPro/Application/SceneDelegate.swift
- CoPro/CoPro/Presentation/BottomTab/ViewController/BottomTabController.swift
- CoPro/CoPro/Presentation/Card/View/CardView.swift
- CoPro/CoPro/Presentation/Card/View/MiniCardGridView.swift
- CoPro/CoPro/Presentation/Card/ViewController/CardViewController.swift
- CoPro/CoPro/Presentation/MyProfile/ViewController/LikeProfileViewController.swift
- 배포전 ui 확인겸 진행
- Resolved: #56
> [Refactor] #56 - UIupdate & BottomTabBar Icon / Fix OnboardingFlow

- CoPro/CoPro/Network/API/Card/CardAPI.swift
- CoPro/CoPro/Presentation/Card/View/CardView.swift
- CoPro/CoPro/Presentation/Card/ViewController/CardViewController.swift
- 카드 데이터 불러오기 체크
- Resolved: #
> [Fix] CardUI Error Fix 

- CoPro/CoPro.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- CoPro/CoPro/Network/API/Card/CardAPI.swift
- CoPro/CoPro/Presentation/Card/ViewController/CardViewController.swift
- Testflight 도중 발견한 문제점 수정
- DropDown UI 수정
- Resolved: #65
> [Feat] #65 - CardView BugFix & UIupdate

- CoPro/CoPro.xcodeproj/project.pbxproj
- CoPro/CoPro/Network/API/Notification/NotificationListAPI.swift
- CoPro/CoPro/Network/DTO/Notification/NotificationListDTO.swift
- CoPro/CoPro/Presentation/BottomTab/ViewController/BottomTabController.swift
- CoPro/CoPro/Presentation/Notification/View/NotificationListCell.swift
- CoPro/CoPro/Presentation/Notification/ViewController/NotificationListViewController.swift
> [Feat] #70 - NotificationList View

- CoPro/CoPro/Presentation/MyProfile/ViewController/EditGithubModalViewController.swift
> [Fix] #64 - Add regex-based GitHub URL validation with alert handling

- CoPro/CoPro/Application/SceneDelegate.swift
- CoPro/CoPro/Presentation/Login/ViewController/LoginViewController.swift
- refreshToken 유효검증 추가
- Resolved: #78
> [Fix] #78 - Fix Login Flow

- CoPro/CoPro/Network/Router/BoardRouter/BoardRouter.swift
- CoPro/CoPro/Presentation/Main/View/CommentChildTableViewCell.swift
- CoPro/CoPro/Presentation/Main/View/CommentTableViewCell.swift
- CoPro/CoPro/Presentation/Main/ViewController/BoardCommentViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/DetailBoardViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/freeViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/noticeViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/recruitViewController.swift
- change View Structure
- Resolved: #85
> [Fix] #85 Change View Structure && Add delete API

- CoPro/CoPro/Application/Info.plist
- CoPro/CoPro/Network/API/Notification/NotificationListAPI.swift
- CoPro/CoPro/Network/DTO/Notification/NotificationListDTO.swift
- CoPro/CoPro/Presentation/Notification/View/NotificationListCell.swift
- CoPro/CoPro/Presentation/Notification/ViewController/NotificationListViewController.swift
- 테이블 셀 중복 데이터 문제 수정
- 알림 리스트 무한스크롤 기능 구현
- 셀 타임 라벨 추가
- Resolved: #88
> [Fix] #88 - Resolved duplicate data issue

- CoPro/CoPro/Presentation/Chat/ViewController/ChatViewController.swift
- CoPro/CoPro/Presentation/Chat/ViewController/OppositeInfoCardViewController.swift
- 상대 정보 카드 뷰 속 like 버튼 기능 구현
- 정보 카드 뷰 UI 스타일 변경
| GIF | <img src = "https://github.com/codingBottle/CoPro-iOS/assets/114901417/d936f156-85a5-4fc7-9d7a-ee9ff16d057c" width ="250">|
- Resolved: #93
> [Feat] #93 - add like button feature, UI style updated at Chat card

- CoPro/CoPro/Network/API/MyProfileAPI/MyProfileAPI.swift
- CoPro/CoPro/Network/DTO/MyProfile/EditGitHubURLDTO.swift
- CoPro/CoPro/Presentation/MyProfile/View/ProfileImageTableViewCell.swift
- CoPro/CoPro/Presentation/MyProfile/ViewController/EditGithubModalViewController.swift
- CoPro/CoPro/Presentation/MyProfile/ViewController/EditMyProfileViewController.swift
- CoPro/CoPro/Presentation/MyProfile/ViewController/MyProfileViewController.swift
- 작업 내용 1
| GIF | <img src = "https://github.com/codingBottle/CoPro-iOS/assets/114901417/23e2e7ab-92f0-47ff-9ea2-1281c4675ab6" width ="250">|
- Resolved: #95
> [Fix] #95 - fixed GitHub alert Bug in Login flow & edit Github DTO

- CoPro/CoPro/Presentation/Card/ViewController/CardViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/DetailBoardViewController.swift
- 채팅방 생성 시도할 때에 존재여부에 따른 분기처리 alert
- alert 이후 channelvc로 이동하지 않던 BugFix
- Resolved: #95
> [Fix] #95 - Fix chat room creation and navigation flow bug

- CoPro/CoPro.xcodeproj/project.pbxproj
- CoPro/CoPro/Network/API/Board/BoardAPI.swift
- CoPro/CoPro/Network/DTO/Board/Request/CommentRequestBody.swift
- CoPro/CoPro/Network/DTO/Board/Response/CommentDTO.swift
- CoPro/CoPro/Network/Router/BoardRouter/BoardRouter.swift
- CoPro/CoPro/Presentation/Main/View/CommentChildTableViewCell.swift
- CoPro/CoPro/Presentation/Main/View/CommentTableViewCell.swift
- CoPro/CoPro/Presentation/Main/View/noticeBoardTableViewCell.swift
- CoPro/CoPro/Presentation/Main/ViewController/AddPostViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/BoardCommentViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/DetailBoardViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/EditPostViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/editCommentViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/freeViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/noticeViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/recruitViewController.swift
- CoPro/CoPro/Presentation/MyProfile/ViewController/MyContributionsViewController.swift
> [Fix] #85 Fix Codes, Add CommentView Edit, Delete

- CoPro/CoPro.xcodeproj/project.pbxproj
- CoPro/CoPro/Network/API/Board/BoardAPI.swift
- CoPro/CoPro/Network/DTO/Board/Request/CreateBoardRequestBody.swift
- CoPro/CoPro/Network/DTO/Board/Response/DetailBoardDTO.swift
- CoPro/CoPro/Network/Router/BoardRouter/BoardRouter.swift
- CoPro/CoPro/Presentation/Main/ViewController/DetailBoardViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/EditPostViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/EditProjectPostViewController.swift
> [Fix] #85 - fix edit post API&View

- CoPro/CoPro/Network/API/Login/LoginAPI.swift
- CoPro/CoPro/Network/API/MyProfileAPI/MyProfileAPI.swift
- CoPro/CoPro/Network/DTO/Notification/ChattingNotificationRequestBody.swift
- CoPro/CoPro/Presentation/Chat/ViewController/ChannelViewController.swift
- CoPro/CoPro/Presentation/Chat/ViewController/ChatViewController.swift
- CoPro/CoPro/Presentation/MyProfile/ViewController/EditGithubModalViewController.swift
- CoPro/CoPro/Presentation/MyProfile/ViewController/EditMyProfileViewController.swift
- 채팅알림 api request 변경에 따른 대응
- First login일 경우 발생하던 flow 버그 픽스
| GIF | <img src = "https://github.com/codingBottle/CoPro-iOS/assets/114901417/923bad01-e702-403c-bfbe-a50fafc2fb9d" width ="250">|
- Resolved: #100
> [Fix] #100 - Chat notification API request changes & First login flow edit

- CoPro/CoPro/Presentation/Chat/ViewController/ChannelViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/AddProjectPostViewController.swift
- 글쓰기 타입 '프로젝트' 일 때에 'mobile' 토클 누락된 것 수정하기
- 채널뷰 프로젝트 토글 숨기기
| GIF | <img src = "https://github.com/codingBottle/CoPro-iOS/assets/114901417/9859b7dd-3f26-4665-bb9b-4e6911e4040c" width ="250">|
- Resolved: #103
> [Fix] #103 - Fix Missing 'Mobile' Toggle in createBoard, Hide Project Toggle in Channel View

- CoPro/CoPro/Network/API/Board/BoardAPI.swift
- CoPro/CoPro/Network/Router/BoardRouter/BoardRouter.swift
- CoPro/CoPro/Presentation/Main/ViewController/AddPostViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/AddProjectPostViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/EditProjectPostViewController.swift
> [Fix] #85 - fix addPost Flow && edit API

- CoPro/CoPro.xcodeproj/project.pbxproj
- CoPro/CoPro/Presentation/MyProfile/View/MemberStatusTableViewCell.swift
- CoPro/CoPro/Presentation/MyProfile/View/MyProfileView.swift
- CoPro/CoPro/Presentation/MyProfile/ViewController/MyProfileViewController.swift
- CoPro/CoPro/Presentation/Notification/ViewController/NotificationListViewController.swift
- NotificationList Navigation
- Resolved: #101
> [Feat] #101 - NotificationList Navigation & SignoutMethod

- CoPro/CoPro/Application/AppDelegate.swift
- Notification Tap Event
- Resolved: #108
> [Feat] #108 - Notification Tap Event

- CoPro/CoPro/Presentation/MyProfile/ViewController/MyProfileViewController.swift
- 로그아웃 기능 구현 최종 완료
| GIF | <img src = "https://github.com/codingBottle/CoPro-iOS/assets/114901417/4838f409-077f-4648-8790-aa68f312c42e" width ="250">|
- Resolved: #110
> [Feat] #110 -  add Finalized Signout feature with updates

- CoPro/CoPro/Presentation/Main/ViewController/AddPostViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/AddProjectPostViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/BoardCommentViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/DetailBoardViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/EditPostViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/EditProjectPostViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/recruitViewController.swift
- CoPro/CoPro/Util/CustomClass/Checkbox.swift
> [Fix] #85 Fix EditView Checked Status && UILayer Error

- CoPro/CoPro.xcodeproj/project.pbxproj
- CoPro/CoPro/Presentation/Main/View/DetailPhotoCollectionViewCell.swift
- CoPro/CoPro/Presentation/Main/View/noticeBoardTableViewCell.swift
- CoPro/CoPro/Presentation/Main/ViewController/DetailBoardViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/DetailPhotoViewController.swift
> [Fea]t #113 Commit for Merge

- CoPro/CoPro/Network/API/Board/BoardAPI.swift
- CoPro/CoPro/Network/DTO/Board/Request/CreateBoardRequestBody.swift
- CoPro/CoPro/Network/Router/BoardRouter/BoardRouter.swift
- CoPro/CoPro/Presentation/Main/View/DetailPhotoCollectionViewCell.swift
- CoPro/CoPro/Presentation/Main/ViewController/AddPostViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/AddProjectPostViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/DetailBoardViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/DetailPhotoViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/EditPostViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/EditProjectPostViewController.swift
> [Feat] #113 - Complete Edit API

- CoPro/CoPro/Presentation/Main/ViewController/AddPostViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/AddProjectPostViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/DetailBoardViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/EditPostViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/EditProjectPostViewController.swift
> [Fix] # 113 - Error Fix

- CoPro/CoPro/Application/SceneDelegate.swift
- CoPro/CoPro/Network/API/Login/LoginAPI.swift
- CoPro/CoPro/Presentation/MyProfile/ViewController/EditGithubModalViewController.swift
- CoPro/CoPro/Presentation/MyProfile/ViewController/EditMyProfileViewController.swift
> [Fix] #117 - fixes for bugs occurring during the first login

- CoPro/CoPro/Presentation/Main/Model/BoardDataModel.swift
- Edit Date Formatter 
- Resolved: #
> [Fix] - boardData Day formatter Error

- CoPro/CoPro.xcodeproj/project.pbxproj
- CoPro/CoPro.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- CoPro/CoPro/Presentation/Main/Model/CommentDataModel.swift
- CoPro/CoPro/Presentation/Main/Model/DetailBoardDataModel.swift
- CoPro/CoPro/Presentation/Main/ViewController/DetailBoardViewController.swift
- 기존 라벨 방식 보다 보기 편하게 마크다운 방식으로 변경
- Resolved: #120
> [Feat] MarkdownView 추가 (공지사항만)

- CoPro/CoPro/Presentation/Main/ViewController/DetailBoardViewController.swift
- href link tap event
- Resolved: #
> [Feat] mark down url link event

- CoPro/CoPro/Presentation/Chat/Model/ChannelFirestoreStream.swift
- CoPro/CoPro/Presentation/Chat/ViewController/ChannelViewController.swift
- CoPro/CoPro/Presentation/MyProfile/ViewController/EditMyProfileViewController.swift
- CoPro/CoPro/Presentation/MyProfile/ViewController/MyProfileViewController.swift
- 닉네임 변경시 firestore 문서도 함께 수정
| GIF | <img src = "https://github.com/codingBottle/CoPro-iOS/assets/114901417/74168f1a-6426-4f67-b6b8-474c1769794d" width ="250">|
- Resolved: #126
> [Fix] #126 - Update Firestore with new nickname on nickname change

- CoPro/CoPro/Presentation/Chat/View/ChannelTableViewCell.swift
- CoPro/CoPro/Presentation/Chat/ViewController/ChannelViewController.swift
- CoPro/CoPro/Presentation/Chat/ViewController/ChatViewController.swift
- CoPro/CoPro/Presentation/MyProfile/ViewController/EditGithubModalViewController.swift
- CoPro/CoPro/Presentation/MyProfile/ViewController/MyProfileViewController.swift
- 채팅방 키보드 이외 영역 터치 시 키보드 내리기
- github url 수정시 textfield 값이 이전 url과 다르다면 isModalInPresentation 활성화
- 채팅방 편집 기능 swipe 활성화 방법 외 한 개 더 추가
| GIF | <img src = "https://github.com/codingBottle/CoPro-iOS/assets/114901417/76ab48cf-2e17-4879-9960-0a15bf7ed056" width ="250">|
- Resolved: #138
> [Feat] MyProfile View, Chat View 1차 피드백 추가 적용

- CoPro/CoPro/Presentation/Main/View/BottomSheetView.swift
- CoPro/CoPro/Presentation/Main/View/CommentTableViewCell.swift
- CoPro/CoPro/Presentation/Main/ViewController/BoardCommentViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/DetailBoardViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/MainViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/SearchBarViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/freeViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/recruitViewController.swift
> [Fix] #134 - Resolve Bug on Likes Button

- CoPro/CoPro/Application/AppDelegate.swift
- CoPro/CoPro/Presentation/Card/View/CardCollectionCellView.swift
- CoPro/CoPro/Presentation/Card/View/MiniCardGridView.swift
- 좋아요가 무한으로 늘어나요 => 수정
- Resolved: #129
> [Fix] #129 - Resolve bug causing infinite increase in likes

- CoPro/CoPro.xcodeproj/project.pbxproj
- CoPro/CoPro.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- CoPro/CoPro/Presentation/BottomTab/ViewController/BottomTabController.swift
- CoPro/CoPro/Presentation/Main/View/CommentChildTableViewCell.swift
- CoPro/CoPro/Presentation/Main/ViewController/DetailBoardViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/MainFloatingViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/MainViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/freeViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/noticeViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/recruitViewController.swift
- CoPro/CoPro/Presentation/MyProfile/ViewController/MyContributionsViewController.swift
- CoPro/CoPro/Presentation/Notification/ViewController/NotificationListViewController.swift
> [Feat] #141 change BottomSheetView into Float Panel Library

- CoPro/CoPro.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> [Fix] - Package.resolved

- CoPro/CoPro/Network/DTO/MyProfile/MyWrittenCommentDTO.swift
- CoPro/CoPro/Presentation/Main/ViewController/BoardCommentViewController.swift
- CoPro/CoPro/Presentation/MyProfile/Model/MyWrittenCommentDataModel.swift
- CoPro/CoPro/Presentation/MyProfile/ViewController/MyContributionsViewController.swift
> [Feat] Implemented comment-to-post navigation

- CoPro/CoPro.xcodeproj/project.pbxproj
- CoPro/CoPro/Network/API/Login/LoginAPI.swift
- CoPro/CoPro/Network/API/MyProfileAPI/MyProfileAPI.swift
- CoPro/CoPro/Network/DTO/Login/WithDrawalDTO.swift
- CoPro/CoPro/Network/DTO/MyProfile/AddProfilePhoto.swift
- CoPro/CoPro/Network/DTO/MyProfile/DeleteProfilePhoto.swift
- CoPro/CoPro/Network/Router/LoginRouter/LoginRouter.swift
- CoPro/CoPro/Network/Router/MyProfileRouter/MyProfileRouter.swift
- CoPro/CoPro/Presentation/Image/ViewController/PhotoViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/AddPostViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/AddProjectPostViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/EditPostViewController.swift
- CoPro/CoPro/Presentation/Main/ViewController/EditProjectPostViewController.swift
- CoPro/CoPro/Presentation/MyProfile/View/ProfileImageTableViewCell.swift
- CoPro/CoPro/Presentation/MyProfile/ViewController/MyProfileViewController.swift
…icture modification
- 작업 내용 1
- Resolved: #151
> [Feat] #151 - Added account deletion and profile picture editing

- CoPro/CoPro/Presentation/Image/ViewController/PhotoViewController.swift
> [Fix] #141 - fix uri

- CoPro/CoPro.xcodeproj/project.pbxproj
- CoPro/CoPro/Network/API/Login/LoginAPI.swift
- CoPro/CoPro/Network/API/MyProfileAPI/MyProfileAPI.swift
- CoPro/CoPro/Network/DTO/Login/DeleteAccountDTO.swift
- CoPro/CoPro/Network/Router/LoginRouter/LoginRouter.swift
- CoPro/CoPro/Presentation/Image/ViewController/PhotoViewController.swift
- CoPro/CoPro/Presentation/MyProfile/View/ProfileImageTableViewCell.swift
- CoPro/CoPro/Presentation/MyProfile/ViewController/MyProfileViewController.swift
> [Refactor] #151 - Refactored profile picture modification, My Profile label & renamed account deletion
